config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  get 'sessions/new'

  #resources :posts
  resources :users
  #resources :welcome
  resources :codeposts,    only: [:create, :destroy, :show]

  root 'static_pages#home'
  get 'users/new'
  get '/about',   to: 'static_pages#about'
  get '/home',   to: 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/allposts', to: 'codeposts#index'
  get    '/finduser', to: 'users#find'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/codepost.rb
class Codepost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }

  validates :title, length: {minimum: 3, maximum: 64}
  validates :html, presence: true
  # validates :css, presence: true
  validates :user_id, presence: true
end

app/controllers/codeposts_controller.rb
class CodepostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def index
    @codeposts = Codepost.all
  end

  def show
    @codepost = Codepost.find(params[:id])
  end

  def create
    @codepost = current_user.codeposts.build(codepost_params)
    if @codepost.save
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @codepost.destroy
    flash[:success] = "Codepost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def codepost_params
      params.require(:codepost).permit(:title, :html, :css)
    end

    def correct_user
      @codepost = current_user.codeposts.find_by(id: params[:id])
      redirect_to root_url if @codepost.nil?
    end
end

app/helpers/codeposts_helper.rb
module CodepostsHelper
end

app/views/codeposts/_codepost.html.erb
<div id="codepost-<%= codepost.id %>" class="feed_post">
  <%= link_to gravatar_for(codepost.user, size: 50), codepost.user %>
  <h3><%= codepost.title %> <span class="codepost_by">by <%= codepost.user.name %></span></h3>
  <%= #simple_format(codepost.html, style: 'background-color: red;')
        text = codepost.html
        text.html_safe
  %><br>
  <span class="timestamp">
    Posted <%= time_ago_in_words(codepost.created_at) %> ago.
  </span>
  <%= link_to 'Show details', codepost %>
  <% if current_user != nil &&
        current_user.id == codepost.user.id %>
      <%= link_to "Delete", codepost, method: :delete,
                  data: { confirm: "You sure?" } %>
  <% end %>
</div>

app/views/codeposts/_form.html.erb
<%= form_for(codepost) do |f| %>
  <% if codepost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(codepost.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% codepost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div id="html_field" class="field">
    <%= f.label :html %>
    <%= f.text_area :html, id => 'html'%>
  </div>

  <div class="field">
    <%= f.label :css %>
    <%= f.text_area :css, id => 'css' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/codeposts/show.html.erb
<div class="bigPanel">
  <p id="notice"><%= notice %></p>
  <p>
    <h1>Title : <%= @codepost.title %></h1>
  </p>

  <p>
    <strong>Text</strong>
    <textarea id="codepost_html" disabled>
    <%= @codepost.html %>
    </textarea>
  </p>

  <%= link_to 'Back', home_path %>
</div>