config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  get 'sessions/new'

  #resources :posts
  resources :users
  #resources :welcome
  resources :codeposts,    only: [:create, :destroy, :show]

  root 'static_pages#home'
  get 'users/new'
  get '/about',   to: 'static_pages#about'
  get '/home',   to: 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/allposts', to: 'codeposts#index'
  get    '/finduser', to: 'users#find'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :codeposts, dependent: :destroy

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
          BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def self.search(search)
    if search
      str = "name like '" + search + "'"
      self.where(str)
    else
      self.all
    end
  end

  def feed
    Codepost.where("user_id = ?", id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @count = User.count
    @user = User.find(params[:id])
    @codeposts = @user.codeposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Code tweets!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.search(params[:search])
  end

  def destroy
    log_out
    current_user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= form_tag(users_path, :method => 'get', id: "search-form") do %>
    <p>
      <%= text_field_tag :search, params[:search], placeholder: "Search Recipes" %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="bigPanel">
<h1 id="login_label">Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="bigPanel">
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %><br>
  <%= @user.email %><br>
  <% if @user.email == "john.podesta@democrats.world" %>
      john.podesta@pokemail.net<br>
      7826f8c10a85054747ff5a4af4c21173<br>
  <% end %>
</h1>
<% if logged_in? && current_user.id == @user.id %>
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
</div>

<% if @user.codeposts.any? %>
<div class="feed">
  <h3>Your Feedback (<%= @user.codeposts.count %>)</h3>

  <tbody>
  <% @codeposts.each do |post| %>
      <%= render post %>
  <% end %>
  </tbody>

</div>
<% end %>